# Generated by Django 5.0.4 on 2024-06-21 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_book_alter_category_name_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
