# Generated by Django 5.0.4 on 2024-06-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
