# Generated by Django 5.0.4 on 2024-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0013_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='feature',
            field=models.CharField(choices=[('bookReview', 'Book-Review'), ('authorSpotlight', 'Author Spotlight'), ('childrensCorner', 'Childrens-Corner'), ('latest', 'Latest'), ('userReview', 'User Review')], default='bookReview', max_length=50),
        ),
    ]
