# Generated by Django 5.0.4 on 2024-06-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_blogpost_status_alter_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='feature',
            field=models.CharField(choices=[('bookReview', 'Book Review'), ('authorSpotlight', 'Author Spotlight'), ('childrensCorner', "Children's Corner"), ('latest', 'Latest'), ('userReview', 'User Review')], default='bookReview', max_length=50),
        ),
    ]
