# Generated by Django 5.0.4 on 2024-06-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
